freebsd_instance:
  image: freebsd-12-0-release-amd64

task:
  install_script: pkg_info && pkg install -y cmake
  build_script: |
    mkdir -p build && cd build
    cmake -DENABLE_NETIF_TESTS=ON ..
    make
    ctest --verbose
